# Generated by Django 4.2.7 on 2024-05-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0003_alter_categories_options_alter_categories_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracks',
            name='category',
        ),
        migrations.AddField(
            model_name='tracks',
            name='categories',
            field=models.ManyToManyField(to='tracks.categories', verbose_name='Категории'),
        ),
    ]
