# Generated by Django 4.2.7 on 2024-05-20 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0005_alter_tracks_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tracks',
            options={'ordering': ('id',), 'verbose_name': 'Трек', 'verbose_name_plural': 'Треки'},
        ),
    ]
