# Generated by Django 4.2.7 on 2024-05-21 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0006_alter_tracks_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название жанра')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'db_table': 'genre',
            },
        ),
        migrations.AlterField(
            model_name='tracks',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='tracks_audio', verbose_name='Аудиофайл'),
        ),
        migrations.AddField(
            model_name='tracks',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracks.genres', verbose_name='Жанр'),
        ),
    ]
